name: CI val

on:
  repository_dispatch:
    types: do-something
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
            java-version: '17'
            distribution: 'temurin'
       - name: Build with Maven
         run: |
           mvn --batch-mode --update-snapshots package  
       - name: Login to Dockerhub
         uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Docker Build and run
         run: |
            docker build -t vkulkarni0303/onlinebookstore .
            docker images -a
            docker push vkulkarni0303/onlinebookstore:latest
