name: CI val

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       - name: Set up JDK 17
         uses: actions/setup-java@v2
         with:
            java-version: '17'
            distribution: 'temurin'
       - name: Build with Maven
         run: |
           mvn --batch-mode --update-snapshots package  
       - name: Login to Dockerhub
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Docker Build and run
         run: |
            docker build  vishwanath0303/onlinebookstore
