name: CI First

on:
  push:
    branches: 
     - master
    # inputs:
    #   image_name:
    #   type: string
    #   default: 'vishwa'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
 #     - name: Set up JDK 17
 #       uses: actions/setup-java@v2
 #       with:
 #         java-version: 17
 #         #distribution: 'adopt'
 #         cache: maven
 #     - name: Build with Maven Wrapper
 #       run: ./mvnw -B package
       - name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
            java-version: '17'
            distribution: 'temurin'
       - name: Build with Maven
         run: mvn --batch-mode --update-snapshots package  

        # Runs a single command using the runners shell
       - name: Login to Dockerhub
         with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Docker Build and run
         run: |
            docker build  vishwanath0303/onlinebookstore
            #docker run -dit -p 8000:8000 vishwanath0303/onlinebookstore
          
          
      # - name: Build and Push the Image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{secrets.DOCKER_USERNAME}}/${{inputs.image_name}}
       
        
          
        
